name: Build OpenCV with GStreamer (Windows)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    env:
      OPENCV_VERSION: 4.10.0
      PYTHON_VERSION: 3.10
      GSTREAMER_VERSION: 1.22.8

    steps:
    # -------------------------------------------------
    # 1) Python
    # -------------------------------------------------
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Python deps
      run: |
        python -m pip install --upgrade pip
        pip install numpy

    # -------------------------------------------------
    # 2) GStreamer (MSVC)
    # -------------------------------------------------
    - name: Install GStreamer
      shell: powershell
      run: |
        $v="${{ env.GSTREAMER_VERSION }}"
        $base="https://gstreamer.freedesktop.org/data/pkg/windows/$v/msvc"
        Invoke-WebRequest "$base/gstreamer-1.0-msvc-x86_64-$v.msi" -OutFile gst.msi
        Invoke-WebRequest "$base/gstreamer-1.0-devel-msvc-x86_64-$v.msi" -OutFile gst-dev.msi
        Start-Process msiexec -ArgumentList "/i gst.msi /quiet /norestart" -Wait
        Start-Process msiexec -ArgumentList "/i gst-dev.msi /quiet /norestart" -Wait

    - name: Add GStreamer to PATH
      run: |
        echo "C:\gstreamer\1.0\msvc_x86_64\bin" >> $env:GITHUB_PATH

    # -------------------------------------------------
    # 3) Clone OpenCV
    # -------------------------------------------------
    - name: Clone OpenCV
      run: |
        git clone https://github.com/opencv/opencv.git
        git clone https://github.com/opencv/opencv_contrib.git
        cd opencv
        git checkout ${{ env.OPENCV_VERSION }}
        cd ..\opencv_contrib
        git checkout ${{ env.OPENCV_VERSION }}

    # -------------------------------------------------
    # 4) Configure (معادل cmake لینوکس)
    # -------------------------------------------------
    - name: Configure OpenCV
      shell: cmd
      run: |
        mkdir opencv\build
        cd opencv\build

        cmake -G "Visual Studio 17 2022" -A x64 ^
          -D CMAKE_BUILD_TYPE=Release ^
          -D OPENCV_EXTRA_MODULES_PATH=..\..\opencv_contrib\modules ^
          -D BUILD_opencv_python3=ON ^
          -D PYTHON3_EXECUTABLE=%pythonLocation%\python.exe ^
          -D PYTHON3_INCLUDE_DIR=%pythonLocation%\include ^
          -D PYTHON3_PACKAGES_PATH=%pythonLocation%\Lib\site-packages ^
          -D WITH_GSTREAMER=ON ^
          -D GSTREAMER_DIR=C:\gstreamer\1.0\msvc_x86_64 ^
          -D WITH_FFMPEG=ON ^
          -D BUILD_TESTS=OFF ^
          -D BUILD_PERF_TESTS=OFF ^
          -D BUILD_EXAMPLES=OFF ^
          ..

    # -------------------------------------------------
    # 5) Build
    # -------------------------------------------------
    - name: Build OpenCV
      run: |
        cd opencv\build
        cmake --build . --config Release --parallel

    # -------------------------------------------------
    # 6) Install Python module
    # -------------------------------------------------
    - name: Install cv2
      shell: powershell
      run: |
        Copy-Item opencv\build\lib\Release\cv2*.pyd `
          "$env:pythonLocation\Lib\site-packages\" -Force

    # -------------------------------------------------
    # 7) Verify
    # -------------------------------------------------
    - name: Verify GStreamer
      run: |
        python - <<EOF
        import cv2
        info = cv2.getBuildInformation()
        print(info)
        assert "GStreamer:                   YES" in info
        EOF
